BOX_IMAGE = "bento/ubuntu-16.04"
WORKER_COUNT = 1
POD_CIDR = "172.18.0.0/16"
API_ADV_ADDRESS = "10.8.8.10"

Vagrant.configure("2") do |config|
  config.vm.define "kube-master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "kube-master"
    subconfig.vm.network :private_network, ip: "10.8.8.10"
    subconfig.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.memory = 2048
    end
    subconfig.vm.provision "shell", path: "common.sh"
    #subconfig.vm.provision "shell", path: "master.sh"
    subconfig.vm.provision "shell", path: "master.sh", args: "#{POD_CIDR} #{API_ADV_ADDRESS}"
  end
  
  (1..WORKER_COUNT).each do |i|
    config.vm.define "kube-worker-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "kube-worker-#{i}"
      subconfig.vm.network :private_network, ip: "10.8.8.#{i + 20}"
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.memory = 1024
      end
      subconfig.vm.provision "shell", path: "common.sh"
    end
  end

  config.vm.provision "shell",
    run: "always",
    inline: "swapoff -a"
end
