apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-app-service
  name: web-app-service
spec:
  ports:
  - name: web-app-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: web-app
  type: NodePort
status:
  loadBalancer: {}